// ビルド時に public/firebase-messaging-sw.js を生成する。
// SW は環境変数を直接読めないため、.env.local の値を埋め込む。
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadEnv } from "dotenv";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

loadEnv({ path: path.join(root, ".env.local") });

const cfg = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "",
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "",
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "",
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "",
};

const sw = `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit
importScripts("https://www.gstatic.com/firebasejs/10.13.2/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.13.2/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(cfg, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title ?? "配当利回りウォッチャー";
  const body = payload.notification?.body ?? "";
  self.registration.showNotification(title, {
    body,
    icon: "/icon-192.png",
    data: { url: payload.fcmOptions?.link ?? "/" },
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data?.url ?? "/";
  event.waitUntil(clients.openWindow(url));
});
`;

const out = path.join(root, "public", "firebase-messaging-sw.js");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, sw, "utf8");

if (!cfg.apiKey) {
  console.warn(
    "[generate-sw] .env.local の Firebase 設定が未入力です。SW のFirebase初期化は空の値で生成されました。",
  );
} else {
  console.log("[generate-sw] public/firebase-messaging-sw.js を生成しました");
}
